<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="OpenTK" Version="5.0.0-pre.15" />
      <PackageReference Include="StbImageSharp" Version="2.30.15" />
      <PackageReference Include="StreamJsonRpc" Version="2.23.32-alpha" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dear ImGui Sample\ImGui_OpenTK.Backends.csproj" />
      <ProjectReference Include="..\Debug\Debug.csproj" />
      <ProjectReference Include="..\GraphicsEngineOpenGL\GraphicsEngineOpenGL.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <Content Include="Editor\Icons\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    


</Project>
