<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Debug\Debug.csproj" />
      <ProjectReference Include="..\Editor\Editor.csproj" />
      <ProjectReference Include="..\GraphicsEngine\GraphicsEngine.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="OpenTK.Windowing.Desktop">
        <HintPath>..\..\.nuget\packages\opentk.windowing.desktop\5.0.0-pre.15\lib\net8.0\OpenTK.Windowing.Desktop.dll</HintPath>
      </Reference>
      <Reference Include="StbImageSharp">
        <HintPath>..\..\.nuget\packages\stbimagesharp\2.30.15\lib\netstandard2.0\StbImageSharp.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
