<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <None Update="Editor\Editor\Icons\csharpIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\fileIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\folderIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\imageIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\ObjIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\sceneIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="OpenTK.Graphics">
        <HintPath>..\..\.nuget\packages\opentk.graphics\5.0.0-pre.15\lib\net8.0\OpenTK.Graphics.dll</HintPath>
      </Reference>
      <Reference Include="OpenTK.Windowing.Desktop">
        <HintPath>..\..\.nuget\packages\opentk.windowing.desktop\5.0.0-pre.15\lib\net8.0\OpenTK.Windowing.Desktop.dll</HintPath>
      </Reference>
      <Reference Include="StbImageSharp">
        <HintPath>..\..\.nuget\packages\stbimagesharp\2.30.15\lib\netstandard2.0\StbImageSharp.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
      <PackageReference Include="Vk" Version="1.0.25" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dear ImGui Sample\ImGui_OpenTK.Backends.csproj" />
      <ProjectReference Include="..\GraphicsEngine\GraphicsEngine.csproj" />
    </ItemGroup>
</Project>
