<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dear ImGui Sample\ImGui_OpenTK.Backends.csproj" />
      <ProjectReference Include="..\InputSystem\InputSystem.csproj" />
      <ProjectReference Include="..\SceneSystem\SceneSystem.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="OpenTK" Version="5.0.0-pre.15" />
      <PackageReference Include="StbImageSharp" Version="2.30.15" />
    </ItemGroup>
    
    <ItemGroup>
      <None Update="Editor\Editor\Icons\csharpIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\fileIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\folderIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\imageIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\ObjIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\sceneIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\fileIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\csharpIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\imageIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\ObjIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Editor\Editor\Icons\sceneIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="Input\" />
    </ItemGroup>


    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
</Project>
